export const HelveticaNeue = 'HelveticaNeue';
export const Georgia = 'Georgia';
export const Ionicons = 'Ionicons';
export const AmericanTypewriter = 'AmericanTypewriter';
export const Cochin = 'Cochin';
export const times = 'Times New Roman';
export const DIN_Alternate = 'DIN Alternate';
export const gillsans = 'Gill Sans';
export const AvenirNext_Regular = 'AvenirNext-Regular';
